export const FUENTES_DISPONIBLES = [
  { valor: "Outfit", etiqueta: "Outfit (moderna)" },
  { valor: "Playfair Display", etiqueta: "Playfair Display (elegante)" },
  { valor: "Poppins", etiqueta: "Poppins (redondeada)" },
  { valor: "Montserrat", etiqueta: "Montserrat (geométrica)" },
  { valor: "Inter", etiqueta: "Inter (neutral)" },
  { valor: "Roboto", etiqueta: "Roboto (clásica)" },
  { valor: "Lora", etiqueta: "Lora (serif legible)" },
  { valor: "Merriweather", etiqueta: "Merriweather (serif robusta)" },
  { valor: "Space Grotesk", etiqueta: "Space Grotesk (grotesca moderna)" },
  { valor: "Sora", etiqueta: "Sora (geométrica contemporánea)" },
  { valor: "DM Sans", etiqueta: "DM Sans (humanista limpia)" },
  { valor: "Plus Jakarta Sans", etiqueta: "Plus Jakarta Sans (corporativa)" },
  { valor: "Manrope", etiqueta: "Manrope (redondeada moderna)" },
  { valor: "Lexend", etiqueta: "Lexend (máxima legibilidad)" },
  { valor: "Nunito Sans", etiqueta: "Nunito Sans (suave amigable)" },
  { valor: "Archivo", etiqueta: "Archivo (grotesca)" },
  { valor: "Bricolage Grotesque", etiqueta: "Bricolage Grotesque (display)" },
  { valor: "Figtree", etiqueta: "Figtree (minimalista)" },
  { valor: "Urbanist", etiqueta: "Urbanist (geométrica)" },
  { valor: "Be Vietnam Pro", etiqueta: "Be Vietnam Pro (moderna)" },
  { valor: "Kumbh Sans", etiqueta: "Kumbh Sans (geométrica)" },
  { valor: "Onest", etiqueta: "Onest (neutral moderna)" },
  { valor: "Instrument Sans", etiqueta: "Instrument Sans (contemporánea)" },
  { valor: "Cormorant Garamond", etiqueta: "Cormorant Garamond (serif refinada)" },
  { valor: "Fraunces", etiqueta: "Fraunces (serif display expresiva)" },
] as const;
