export type ClaveDrawer =
  | "informacion"
  | "contacto"
  | "ubicacion"
  | "redes"
  | "regional"
  | "tienda"
  | "whatsapp"
  | "mercadopago"
  | "pagos"
  | "mantenimiento"
  | "avanzado"
  | "seo"
  | "legal"
  | "footer";
